apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-holder
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
data:
  namespace: "{{ .Release.Namespace }}"