{{ if .Values.network_policies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: network-policeis
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openunison-to-activemq
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: network-policeis
    app.kubernetes.io/part-of: openunison
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{ .Values.network_policies.namespace_label }}: {{ .Release.Namespace }}
  podSelector:
    matchLabels:
      app: amq-{{ .Release.Name }}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openunison-to-html
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: network-policeis
    app.kubernetes.io/part-of: openunison
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{ .Values.network_policies.namespace_label }}: {{ .Release.Namespace }}
  podSelector:
    matchLabels:
      app: {{ .Values.openunison.html.prefix }}-{{ .Values.openunison.portal_release_name }}
  policyTypes:
  - Ingress
{{ if .Values.network_policies.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: network-policeis
    app.kubernetes.io/part-of: openunison
spec:
  podSelector:
    matchLabels:
      application: openunison-{{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: {{ range $key,$value := .Values.network_policies.ingress.labels }}
            {{ $key }}: {{ $value }}
        {{ end }}
  policyTypes:
  - Ingress

{{ if and (eq .Values.enable_impersonation true) (eq .Values.impersonation.use_jetstack true)  }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oidc-proxy-allow-from-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: network-policeis
    app.kubernetes.io/part-of: openunison
spec:
  podSelector:
    matchLabels:
      app: kube-oidc-proxy-{{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: {{ range $key,$value := .Values.network_policies.ingress.labels }}
            {{ $key }}: {{ $value }}
        {{ end }}
  policyTypes:
  - Ingress
{{ end }}

{{ end }}
{{ if .Values.network_policies.monitoring.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: network-policeis
    app.kubernetes.io/part-of: openunison
spec:
  podSelector:
    matchLabels:
      application: openunison-{{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: {{ range $key,$value :=  .Values.network_policies.monitoring.labels }}
            {{ $key }}: {{ $value }}
        {{ end }}
  policyTypes:
  - Ingress
{{ end }}
{{ if .Values.network_policies.apiserver.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: network-policeis
    app.kubernetes.io/part-of: openunison
spec:
  podSelector:
    matchLabels:
      application: openunison-{{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: {{ range $key,$value :=  .Values.network_policies.apiserver.labels }}
            {{ $key }}: {{ $value }}
        {{ end }}
  policyTypes:
  - Ingress
{{ end }}
{{ end }}
