{{ if .Values.saml }}
{{ if .Values.saml.metadata_xml_b64 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: saml2-metadata
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
data:
  metadata.xml: |-
{{ indent 4 (b64dec .Values.saml.metadata_xml_b64) }}
{{ end }}
{{ end }}