{{ if not .Values.openunison.enable_provisioning }}
apiVersion: openunison.tremolo.io/v1
kind: Target
metadata:
  name: jitdb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-targets
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  className: com.tremolosecurity.provisioning.providers.K8sCrdUserProvider
  params:
  - name: k8sTarget
    value: k8s
  - name: nameSpace
    value: {{ .Release.Namespace }}
  secretParams: []
  targetAttributes:
  - name: first_name
    source: first_name
    sourceType: user
  - name: last_name
    source: last_name
    sourceType: user
  - name: email
    source: email
    sourceType: user
  - name: email_verified
    source: email_verified
    sourceType: user
  - name: sub
    source: sub
    sourceType: user
  - name: uid
    source: uid
    sourceType: user
{{ end }}