{{ if .Values.github }}
---
apiVersion: openunison.tremolo.io/v1
kind: CustomAuthorization
metadata:
  name: github
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-customaz
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  className: com.tremolosecurity.unison.proxy.auth.github.GithubTeamRule
  params: {}
{{ end }}